project:
  type: book
  output-dir: docs

book:
  title: "Willow Tit Project"
  chapters:
    - index.qmd
    - intro.qmd
    - species.qmd
    - method.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



