---
output: html_document
editor_options: 
  chunk_output_type: console
bibliography: references.bib
---

# Encounter Rate

As stated in the previously, I am still getting to grips with the theory and application of species distribution models. The eBird Willow Tit data is an excellent resource to learn how such models work using real-world data. However, many of the decisions and parameters of the model may not be the most suitable for UK Willow Tit data. I am still learning how best to approach this. I am also happy for any insight. So please feel free to submit suggestions or comments on [GitHub](https://github.com/jacvig/WillowTit2024/issues).

The encounter rate will measure the probability of an observer detecting a species during a standard birding session. In this case, it will be an eBird checklist. Ultimately, it is occupancy (the probability a species occurs at a site) that is most useful, but this is hard to measure with citizen-science data due to the variation in detectability. To address this, it can be useful to include effort covariates in the model so that the encounter rate is proportional to occupancy. Since Willow Tits in the UK are harder to detect, the encounter rate will be substantially lower than the occupancy rate.

The model developed by @StrimasMackey addresses class imbalance and spacial bias through spatial subsampling. A balanced random forest model is then trained and calibrated before using it to predict encounter rates across the study area and mapping these. The calibration model is trained by predicting the encounter rate for each checklist in the training set, then fitting a binomial Generalized Additive Model (GAM) with the real observed encounter rate as the response and the predicted encounter rate as the predictor variable. The full R code is available in the file *EncounterRate.R* on [GitHub](https://github.com/jacvig/WillowTit2024).
