---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Environmental Variables

This project wanted to look at associations between Willow Tit occurrence and environmental variables to see if any relationships were identified that could then be used as predictors of distribution in areas that were not sampled.

Landcover and elevation were chosen as suitable variables with guidance and recommendations as outlined by @StrimasMackey followed. A prediction grid was then created, and lastly the data were mapped. For the full R code, see the file *EnvironmentalVariables.R* on [GitHub](https://github.com/jacvig/WillowTit2024).

## Landcover

The [MODIS MCD12Q1 v061](https://www.earthdata.nasa.gov/data/catalog/lpcloud-mcd12q1-061) product was the chosen dataset for landcover variables as it provides global coverage at 500m spacial resolution from 2001-present. The University of Maryland classification system was used.

First, the MODIS files were downloaded and processed into a raster file, see the file *Processing_MODIS_files.R* on [GitHub](https://github.com/jacvig/WillowTit2024).

Then, the landcover class was extracted for each checklist location by creating a 3km area around the checklist location, which is considered sufficient to account for spatial precision, and calculating two metrics: a measure of composition and a measure of configuration. These are reliable metrics for calculating environmental covariates in distribution models.

## Elevation

Elevation data was downloaded from the [EarthEnv](https://www.earthenv.org/topography) website at 1km resolution. Then, both the mean and standard deviation of the elevation for the 3km checklist neighborhood was calculated.

The landcover and elevation variables were then joined to the checklkist data.

## Prediction grid
