# Welcome {.unnumbered}

This is my project site for modelling Willow Tit population distribution in the UK.

The project consists of a short introduction about the species alongside efforts to model the available data to show encounter rate and relative abundance. The full R code for this project is openly available from the [WillowTit2024](https://github.com/jacvig/WillowTit2024) repository on GitHub. It is a work in progress and will be updated and added to as I am able.

The aims of this project are three-fold, and all personal. First, I wish to add to the knowledge of Willow Tit populations in the UK using openly available citizen-science data. As one of my favourite species, I am regularly involved in surveying populations and have witnessed a decline in the species locally. My interest and concern have naturally led me to learn more about ecology, conservation, and environmental science, but not having formally studied these fields, this project allows me to focus my interest in a way that is valuable to me. And third, it offers a way to improve my data science and programming skills, neither of which were ever something I thought I would pursue but are becoming more necessary in my work as a data management librarian.

To submit fixes or suggest additions, please file an [issue on GitHub](https://github.com/jacvig/WillowTit2024/issues).
